### ISSUE TITLE
落ちる不具合

### ISSUE THREAD

**Issue by Nishisonic** [Nishisonic/AddImage#1]
> 画像追加exVer.2.0.3を使っていますが、急に航海日誌本体が落ちるようになってしまいました（今日だけで3回）。
> タイミングやトリガーは不明ですがとりあえず報告を

**Comment by Nishisonic** [comment]
> > 82

2016-10-17 09:13:10,458 FATAL l.g.ApplicationMain [main] メインスレッドが異常終了しました
org.eclipse.swt.SWTException: Failed to execute runnable (org.eclipse.swt.SWTError: No more handles)
    at org.eclipse.swt.SWT.error(Unknown Source) ~[swt.jar:?]
    at org.eclipse.swt.SWT.error(Unknown Source) ~[swt.jar:?]
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source) ~[swt.jar:?]
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source) ~[swt.jar:?]
    at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source) ~[swt.jar:?]
    at logbook.gui.ApplicationMain.open(ApplicationMain.java:411) ~[logbook.jar:?]
    at logbook.gui.WindowBase.restore(WindowBase.java:866) ~[logbook.jar:?]
    at logbook.gui.ApplicationMain.restore(ApplicationMain.java:1442) ~[logbook.jar:?]
    at logbook.gui.ApplicationMain.main(ApplicationMain.java:379) [logbook.jar:?]
Caused by: org.eclipse.swt.SWTError: No more handles
    at org.eclipse.swt.SWT.error(Unknown Source) ~[swt.jar:?]
    at org.eclipse.swt.SWT.error(Unknown Source) ~[swt.jar:?]
    at org.eclipse.swt.SWT.error(Unknown Source) ~[swt.jar:?]
    at org.eclipse.swt.graphics.Image.createGdipImage(Unknown Source) ~[swt.jar:?]
    at org.eclipse.swt.graphics.GC.drawImage(Unknown Source) ~[swt.jar:?]
    at org.eclipse.swt.graphics.GC.drawImage(Unknown Source) ~[swt.jar:?]
    at jdk.nashorn.internal.scripts.Script$Recompilation$132$12161AAA$^eval_.getSynthesisItemIconImage(<eval>:359) ~[?:?]
    at jdk.nashorn.internal.scripts.Script$Recompilation$131$10090A$^eval_.create$L:255(<eval>:257) ~[?:?]
    at jdk.nashorn.javaadapters.java.util.function.Consumer.accept(Unknown Source) ~[?:?]
    at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_101]
    at jdk.nashorn.internal.scripts.Script$Recompilation$55$8013AAA$^eval_.create(<eval>:255) ~[?:?]
    at logbook.gui.logic.TableItemCreator$$NashornJavaAdapter.create(Unknown Source) ~[?:?]
    at logbook.scripting.TableItemCreatorProxy$CreateMethod.invoke(TableItemCreatorProxy.java:30) ~[logbook.jar:?]
    at logbook.scripting.ScriptLoader$Script.invoke(ScriptLoader.java:126) ~[logbook.jar:?]
    at logbook.scripting.TableItemCreatorProxy.create(TableItemCreatorProxy.java:49) ~[logbook.jar:?]
    at logbook.gui.AbstractTableDialog.setTableBody(AbstractTableDialog.java:436) ~[logbook.jar:?]
    at logbook.gui.AbstractTableDialog.reloadTable(AbstractTableDialog.java:389) ~[logbook.jar:?]
    at logbook.gui.AbstractTableDialog$CyclicReloadTask$1.run(AbstractTableDialog.java:1062) ~[logbook.jar:?]
    at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source) ~[swt.jar:?]
    ... 7 more

**Comment by Nishisonic** [comment]
原因は装備アイコン生成時のエラーとなっているが、根本的な原因はメモリ不足(dispose()し忘れ)にある。
これを自分はフォントか色が原因でないかと推測し、Ver2.0.4にて修正を行った。
続報はまだ来ていないので、ちゃんと修正出来ているかは不明。

**Comment by Nishisonic** [comment]
> 画像追加exVer.2.0.6で航海日誌が落ちました（スレの上でも書いた者です）
> 3-3で秋刀魚漁中にボスマスで大破艦が出る＞戦闘終了＞落ちる、って感じでした。一応ログも張っておきます。前回と同じかな…

2016-10-21 21:17:53,897 FATAL l.g.ApplicationMain [main] メインスレッドが異常終了しました
org.eclipse.swt.SWTException: Failed to execute runnable (org.eclipse.swt.SWTError: No more handles)
    at org.eclipse.swt.SWT.error(Unknown Source) ~[swt.jar:?]
    at org.eclipse.swt.SWT.error(Unknown Source) ~[swt.jar:?]
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source) ~[swt.jar:?]
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source) ~[swt.jar:?]
    at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source) ~[swt.jar:?]
    at logbook.gui.ApplicationMain.open(ApplicationMain.java:411) ~[logbook.jar:?]
    at logbook.gui.WindowBase.restore(WindowBase.java:866) ~[logbook.jar:?]
    at logbook.gui.ApplicationMain.restore(ApplicationMain.java:1442) ~[logbook.jar:?]
    at logbook.gui.ApplicationMain.main(ApplicationMain.java:379) [logbook.jar:?]
Caused by: org.eclipse.swt.SWTError: No more handles
    at org.eclipse.swt.SWT.error(Unknown Source) ~[swt.jar:?]
    at org.eclipse.swt.SWT.error(Unknown Source) ~[swt.jar:?]
    at org.eclipse.swt.SWT.error(Unknown Source) ~[swt.jar:?]
    at org.eclipse.swt.graphics.Image.createGdipImage(Unknown Source) ~[swt.jar:?]
    at org.eclipse.swt.graphics.GC.drawImage(Unknown Source) ~[swt.jar:?]
    at org.eclipse.swt.graphics.GC.drawImage(Unknown Source) ~[swt.jar:?]
    at jdk.nashorn.internal.scripts.Script$Recompilation$156$16870AAA$^eval_.getSynthesisItemIconImage(<eval>:471) ~[?:?]
    at jdk.nashorn.internal.scripts.Script$Recompilation$155$12449A$^eval_.create$L:298(<eval>:300) ~[?:?]
    at jdk.nashorn.javaadapters.java.util.function.Consumer.accept(Unknown Source) ~[?:?]
    at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_111]
    at jdk.nashorn.internal.scripts.Script$Recompilation$53$10144AAA$^eval_.create(<eval>:298) ~[?:?]
    at logbook.gui.logic.TableItemCreator$$NashornJavaAdapter.create(Unknown Source) ~[?:?]
    at logbook.scripting.TableItemCreatorProxy$CreateMethod.invoke(TableItemCreatorProxy.java:30) ~[logbook.jar:?]
    at logbook.scripting.ScriptLoader$Script.invoke(ScriptLoader.java:126) ~[logbook.jar:?]
    at logbook.scripting.TableItemCreatorProxy.create(TableItemCreatorProxy.java:49) ~[logbook.jar:?]
    at logbook.gui.AbstractTableDialog.setTableBody(AbstractTableDialog.java:436) ~[logbook.jar:?]
    at logbook.gui.AbstractTableDialog.reloadTable(AbstractTableDialog.java:389) ~[logbook.jar:?]
    at logbook.gui.AbstractTableDialog$CyclicReloadTask$1.run(AbstractTableDialog.java:1062) ~[logbook.jar:?]
    at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source) ~[swt.jar:?]
    ... 7 more

**Comment by Nishisonic** [comment]
解決できてないみたい(非常に不味い)

**Comment by Nishisonic** [comment]
一旦System.gc();でガベージコレクションを優先的に呼び出す形にして、メモリを空けてもらうことにした
80%以上メモリを使うと実行される

これでも落ちる場合は毎回呼び出す形or基準をさらに引き下げる形になると思われる

**Comment by Nishisonic** [comment]
一つの可能性として、このスクリプトは画像リソースをメモリ上に展開して読み込み時間を短縮している関係上、割り当てられているメモリをかなり使うため、環境によってはガベージコレクションのタイミングまでにメモリを使い切ってしまう可能性が考えられる。
こちらの環境でも割り振られている内の最高95%ぐらいまでメモリを使うため、環境次第では使い切ると思われる。

**Comment by Nishisonic** [comment]
![debug.log](https://pbs.twimg.com/media/Cvc6zZrVIAAdQhf.png)
どうやらChangingの際の処理が杜撰っぽい

**Comment by Nishisonic** [comment]
Changingの後にはDisposeが挟まれてないといけないが、挟まれていない
つまり、dispose()処理がされてない

**Comment by Nishisonic** [comment]
![image](https://cloud.githubusercontent.com/assets/12210425/19626229/ec167db4-9967-11e6-9781-00c7de5a2e9f.png)
![image](https://cloud.githubusercontent.com/assets/12210425/19626237/0a10d2b0-9968-11e6-875f-a19e29bc33b0.png)

**Comment by Nishisonic** [comment]
Existing -> Changing -> Dispose -> Existing ...

**Comment by Nishisonic** [comment]
~~Ver2.0.8で修正加えたので、取り敢えず経過観察~~

落ちたのでまた再検証行き

**Comment by Nishisonic** [comment]
Ver2.0.9でお風呂に入りたい艦娘のバグを修正

たぶんバグ直せたので、次commitする際に閉じる
